title: 🤖 RobotApp-0_0
description: Our company is launching the RoboTasker 5000 (RT5000) to support families with basic tasks in their household. This repo displays interview questions/requirements for 4 different receipes.
show_downloads: false
theme: jekyll-theme-merlot
