title: Merlot theme
description: Scenario: Our company is launching the RoboTasker 5000 (RT5000) to support families with basic tasks in their household. This repo displays interview question/ requirements for 4 different receipes.
show_downloads: false
theme: jekyll-theme-merlot
